name: Deploy

on: 
  push:  
    branches: 
    - main   

jobs: 
  deploy_lambda:
    runs-on: ubuntu-latest 
    steps:

      - uses: actions/checkout@v2  
      - uses: actions/setup-node@v2
        with:  
          node-version: '20' 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
      - name: deploy
        run: |
          zip -j deploy.zip ./*
          aws lambda update-function-code --function-name=mono-ynab-sync --zip-file=fileb://deploy.zip